# Notes
# SVG Builder: https://jakearchibald.github.io/svgomg/
# Example: https://matthijsjanssens.github.io | https://github.com/matthijsjanssens/matthijsjanssens.github.io
# Example 2: https://lilianweng.github.io | https://github.com/lilianweng/lilianweng.github.io


baseURL = 'https://datavistics.github.io/'
languageCode = 'en-us'
title = "Derek Thomas's AI Blog"
theme = ['hugo-notice', 'PaperMod']
resourceDir = "resources"
enableEmoji = true

SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "G-9ZGDRP3XHT"
enableRobotsTXT = true

buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Derek's AI Blog"
description = "Derek's AI Blog"
keywords = ["AI", "Blog", "LLMs", "Learn LLMs", "Arabic NLP", "NLP"]
author = "Derek Thomas"
images = ["https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/1670323064870-638eb5f949de7ae552dd6211.jpeg?w=200&h=200&f=face"]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = false
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = true
tocopen = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = false
noClasses = false

[params.label]
text = "Home"
icon = "/apple-touch-icon.png"
iconHeight = 35

[params.homeInfoParams]
Title = "Hi there 👋🏾,  I'm Derek"
Content = """
I'm a [Machine Learning Success Engineer at 🤗](https://huggingface.co)

Welcome to my personal **AI Blog**!

Please note that all views are entirely my own.
"""
picture = "https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/1670323064870-638eb5f949de7ae552dd6211.jpeg?w=200&h=200&f=face"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/dthomas/"

[[params.socialIcons]]
name = "huggingface"
url = "https://huggingface.co/derek-thomas"

[params.analytics.google]
SiteVerificationTag = "G-9ZGDRP3XHT"

[params.assets]
favicon = "assets/favicon.ico"
apple_touch_icon = "assets/apple_touch_icon.png"
favicon16x16 = "assets/favicon-16x16.png"
favicon32x32 =  "assets/favicon-32x32.png"

[params.cover]
hidden = false
hiddenInList = true
hiddenInSingle = true

[params.editPost]
URL = "https://github.com/datavistics/datavistics.github.io/tree/main/content"
Text = "Suggest Changes"
appendFilePath = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

[[menu.main]]
identifier = "Archive"
name = "📁 Archive"
url = "/archives/"
weight = 20

[[menu.main]]
identifier = "Search"
name = "🔍 Search"
url = "/search/"
weight = 20

[[menu.main]]
identifier = "Tags"
name = "🏷️ Tags"
url = "/tags/"
weight = 20

[outputs]
home = [ 'HTML', 'RSS', 'JSON' ]